# Site settings
title:       Jonathon Belotti [thundergolfer]
author:      Jonathon Belotti
description: "No hugs, some learning"
baseurl:     ""
url:         "https://thundergolfer.github.io/"
date_format: "%b %-d, %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-113168316-1
google_tag_manager:
# Bing services
bing_verification:

# Optional features
show_related_posts:   false
show_post_footers:    True
show_social_icons:    True
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: 'jonathonbelottiblog'

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: thundergolfer
bitbucket_username:
stackoverflow_id:
twitter_username: jonobelotti_io
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: jonathonbelotti
angellist_username:
#medium_id: thundergolfer
youtube_channel_id: UCSP7fMKwmaXaZhViAV2Vgvg
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: False # Looks Ugly atm
# Change to 'true' to enable individual icons
share_facebook: True
share_twitter: True
share_googleplus: True
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: True
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share this post!'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data', 'footnotes']
permalink:    pretty
paginate:     6
paginate_path: "/blog/:num/"
sass:
  compressed: true
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

collections_dir: collections
collections:
  reviews:
    output: true
  portfolio:
    output: true
